### ISSUE TITLE
Build fails on pull request

### ISSUE THREAD

**Issue by trailmax** [AMVSoftware/Cake.SqlServer#14]
Build fails on pull request. See https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/51-cendkfse

>Executing GenerateSetVersionMessage for 'AppVeyor'.
ERROR [01/03/17 16:38:51:97] An unexpected error occurred:
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables)
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [01/03/17 16:38:51:97] 
INFO [01/03/17 16:38:51:97] Attempting to show the current git graph (please include in issue): 
INFO [01/03/17 16:38:51:97] Showing max of 100 commits

**Comment by trailmax** [comment]
Fixed by help from Appveyor team https://github.com/appveyor/ci/issues/1252
